-- MySQL Script generated by MySQL Workbench
-- Mon Dec 29 20:59:09 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Treninzi
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Treninzi
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Treninzi` DEFAULT CHARACTER SET utf8 ;
USE `Treninzi` ;

-- -----------------------------------------------------
-- Table `Treninzi`.`Trening`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Treninzi`.`Trening` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `naziv` NVARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Treninzi`.`Sesija`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Treninzi`.`Sesija` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `datum` DATE NOT NULL,
  `vreme_pocetka` TIME NULL,
  `vreme_zavrsetka` TIME NULL,
  `trajanje` TIME NULL,
  `fk_trening_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `FOREIGN KEY(fk_trening_id)` (`fk_trening_id` ASC) VISIBLE,
  INDEX `INDEX(datum)` (`datum` ASC) VISIBLE,
  CONSTRAINT `fk_Sesija_Naziv_treninga1`
    FOREIGN KEY (`fk_trening_id`)
    REFERENCES `Treninzi`.`Trening` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Treninzi`.`Vezba`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Treninzi`.`Vezba` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `naziv` NVARCHAR(30) NOT NULL,
  `tip_opreme` NVARCHAR(20) NULL,
  PRIMARY KEY (`id`),
  INDEX `INDEX(naziv)` (`naziv` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Treninzi`.`Sesija_vezba`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Treninzi`.`Sesija_vezba` (
  `id` INT NOT NULL,
  `fk_sesija_id` INT NOT NULL,
  `fk_vezba_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `INDEX(fk_vezba_id)` (`fk_vezba_id` ASC) INVISIBLE,
  INDEX `INDEX(fk_sesija_id)` (`fk_sesija_id` ASC) INVISIBLE,
  UNIQUE INDEX `UNIQUE(fk_vezba_id, fk_sesija_id)` (`fk_sesija_id` ASC, `fk_vezba_id` ASC) VISIBLE,
  CONSTRAINT `fk_Sesija_vezba_Sesija`
    FOREIGN KEY (`fk_sesija_id`)
    REFERENCES `Treninzi`.`Sesija` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sesija_vezba_Vezba1`
    FOREIGN KEY (`fk_vezba_id`)
    REFERENCES `Treninzi`.`Vezba` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Treninzi`.`Podaci_o_vezbi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Treninzi`.`Podaci_o_vezbi` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fk_sesija_vezba_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `INDEX(fk_sesija_vezba_id)` (`fk_sesija_vezba_id` ASC) VISIBLE,
  CONSTRAINT `fk_Podaci_o_vezbi_Sesija_vezba1`
    FOREIGN KEY (`fk_sesija_vezba_id`)
    REFERENCES `Treninzi`.`Sesija_vezba` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Treninzi`.`Podaci_snaga`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Treninzi`.`Podaci_snaga` (
  `podaci_o_vezbi_id` INT NOT NULL,
  `tezina` DECIMAL NULL,
  `broj_sesija` INT NULL,
  `broj_ponavljanja` INT NULL,
  PRIMARY KEY (`podaci_o_vezbi_id`),
  INDEX `INDEX(podaci_o_vezbi_id)` (`podaci_o_vezbi_id` ASC) VISIBLE,
  CONSTRAINT `fk_Podaci_snaga_Podaci_o_vezbi1`
    FOREIGN KEY (`podaci_o_vezbi_id`)
    REFERENCES `Treninzi`.`Podaci_o_vezbi` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Treninzi`.`Podaci_kardio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Treninzi`.`Podaci_kardio` (
  `podaci_o_vezbi_id` INT NOT NULL,
  `vreme_trcanja` TIME NULL,
  `brzina` DECIMAL NULL,
  `nagib` DECIMAL NULL,
  PRIMARY KEY (`podaci_o_vezbi_id`),
  INDEX `INDEX(podaci_o_vezbi_id)` (`podaci_o_vezbi_id` ASC) VISIBLE,
  CONSTRAINT `fk_Podaci_snaga_Podaci_o_vezbi10`
    FOREIGN KEY (`podaci_o_vezbi_id`)
    REFERENCES `Treninzi`.`Podaci_o_vezbi` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Treninzi`.`Trening_vezba`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Treninzi`.`Trening_vezba` (
  `fk_trening_id` INT NOT NULL,
  `fk_vezba_id` INT NOT NULL,
  PRIMARY KEY (`fk_trening_id`, `fk_vezba_id`),
  INDEX `INDEX(fk_vezba_id)` (`fk_vezba_id` ASC) VISIBLE,
  INDEX `INDEX(fk_trening_id)` (`fk_trening_id` ASC) VISIBLE,
  CONSTRAINT `fk_Naziv_treninga_has_Vezba_Naziv_treninga1`
    FOREIGN KEY (`fk_trening_id`)
    REFERENCES `Treninzi`.`Trening` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Naziv_treninga_has_Vezba_Vezba1`
    FOREIGN KEY (`fk_vezba_id`)
    REFERENCES `Treninzi`.`Vezba` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
